### ISSUE TITLE
cygheap base mismatch detected

### ISSUE THREAD

**Issue by kenuematsu09** [yifanlu/psvimgtools#10]
When I run
`psvimg-create -n app -K <myKey> app PCSG90096/app`

It returns an error:

`cygheap base mismatch detected - 0x1605408/0xF95408.
This problem is probably due to using incompatible versions of the cygwin DLL.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.
      0 [main] psvimg-create 5936 fork: child -1 - forked process 12876 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
fork: Resource temporarily unavailable`

**Comment by yifanlu** [comment]
Your error message literally gives you the solution.

**Comment by kenuematsu09** [comment]
I have no Cygwin installed on my PC. The cygwin1.dll file that I only have was from the zip that I downloaded.

**Comment by yifanlu** [comment]
github is not a support forum, thanks
