### ISSUE TITLE
Possible 32-bit Win version?

### ISSUE THREAD

**Issue by HerrFuchs517** [yifanlu/psvimgtools#2]
I would like to kindly ask if it might be possible for you to compile and release a 32-bit windows version for some of the people that are only using these types of windows.

I would do it myself but am lacking in competence on the subject. I tried searching if someone has done so already, but without results.

Perhaps this would not be a big difficulty...

Thanks.

**Comment by yifanlu** [comment]
I hate windows and already wasted too much time getting win64 to compile. So I'm not wasting any more time with windows.

**Comment by pablikenemy** [comment]
So sadly that There's a lot of people that Cant enjoy this because they are on 32bit, i hope that some can make an x86 versión and then every one can use this tools  without any kind of "pregiudice" if is windows or not..

**Comment by CelesteBlue-dev** [comment]
Don't worry, someone is working on a GUI version, for Win, Linux and what do you want more ? xD

**Comment by pablikenemy** [comment]
Really !? Man i hope so!! Thanks for answer ...
