### ISSUE TITLE
MIT license

### ISSUE THREAD

**Issue by CelesteBlue-dev** [yifanlu/psvimgtools#4]
Dear yifan lu, can we release a GUI version of your tool ?
And is there some prerequisites to publish it ?
I mean licenses, credits or anything needed.
Regards and thank you very much.

**Comment by yifanlu** [comment]
https://github.com/yifanlu/psvimgtools/blob/master/LICENSE

https://tldrlegal.com/license/mit-license

You can do pretty much anything you want with it (sell it, relicense it, etc) provided you do not remove the copyright from the source files.
