### ISSUE TITLE
Can't execute built file

### ISSUE THREAD

**Issue by DaCodaHUB** [yifanlu/psvimgtools#9]
I keep getting "cannot execute binary file: Exec format error" when I tried to run it.

file psvimg-create output:
psvimg-create: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=5950c3436820e99f1b231edbb367191e70bcbee1, not stripped

Can anyone help?

**Comment by yifanlu** [comment]
This is not a support forum.
